# AUC ML LabExercise - Neural Networks
Ungraded exercise, deadline Friday 3 November, 23:59.


In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


To use the Neural Networks package you first need to install the scikit-neuralnetwork. Install it through your Anaconda Navigator to avoid version mismatches. You can find the documentation here: 
http://scikit-learn.org/stable/modules/neural_networks_supervised.html

Useful link:
http://scikit-learn.org/stable/auto_examples/classification/plot_classification_probability.html#sphx-glr-auto-examples-classification-plot-classification-probability-py

In [8]:
#In this notebook we will work with the, commonly used, Iris dataset. 
#Please read the description of the dataset here:
#http://scikit-learn.org/stable/auto_examples/datasets/plot_iris_dataset.html

#First we import all the modules that you need for this exrecise
from sklearn import datasets # to load the dataset
from sklearn.preprocessing import StandardScaler # to normalize data (NN is very sensitive to this!)
from sklearn.model_selection import train_test_split #to split in train and test set
from sklearn.linear_model import LogisticRegression #logistic regression classifier
from sklearn.neural_network import MLPClassifier # neural network classifier
from sklearn.model_selection import cross_val_score #BONUS: to tune parameters using cross-validation


#Step 1: Load Iris dataset.
iris = datasets.load_iris()

#Step 2: Save the features (data) and the labels (target) in separate variables.
features = iris.data
labels = iris.target

#Step 3: Normalize your data. Do it 'by hand' using a for-loop or use the StandardScaler() function.
scaler = StandardScaler()
features_norm = scaler.fit_transform(features)

#Step 4: Split the dataset in train and test sets. 
#You can either do it 'by hand' or use the train_test_split() function.
train_test = train_test_split(features_norm, shuffle=False)
train = train_test[0]
test = train_test[1]
#y = 
print(type(labels))
print(type(train))
print(labels)
print(train)
#print(test)

#Step 5: Load logistic regression.
# Study in the documentation all the arguments that the function takes as input and returns as output.
# Choose some initial values to start with and experiment with them after you get to Step 8.
logistic = LogisticRegression(C=1.0, penalty='l1')

#Step 6: Load NN Classifer
# Study in the documentation all the arguments that the function takes as input and returns as output.
# Choose some initial values to start with and experiment with them after you get to Step 8.
classifier = MLPClassifier(alpha=1)

# Step 7: Training
# Train both classifier, uising fit() function.
logistic.fit(train, labels[:112])
classifier.fit(train, labels[113:150])

# Step 8: Testing/Prediction
# Print the score for both classifiers on the test set, using score() function.
print(logistic.score(test, labels[:112]))
print(classifier.score(test, labels[113:150]))

# BONUS Step 9: Look at your cross validation error 
# and discover how to tune your NN parameters with cross validation
# Print the scores and also print the mean (accuracy) and std (95% confidence interval) of your scores


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[[ -9.00681170e-01   1.03205722e+00  -1.34127240e+00  -1.31297673e+00]
 [ -1.14301691e+00  -1.24957601e-01  -1.34127240e+00  -1.31297673e+00]
 [ -1.38535265e+00   3.37848329e-01  -1.39813811e+00  -1.31297673e+00]
 [ -1.50652052e+00   1.06445364e-01  -1.28440670e+00  -1.31297673e+00]
 [ -1.02184904e+00   1.26346019e+00  -1.34127240e+00  -1.31297673e+00]
 [ -5.37177559e-01   1.95766909e+00  -1.17067529e+00  -1.05003079e+00]
 [ -1.50652052e+00   8.00654259e-01  -1.34127240e+00  -1.18150376e+00]
 [ -1.02184904e+00   8.00654259e-01  -1.28440670e+00  -1.31297673e+00]
 [ -1.74885626e+00  -3.56360566e-01  -1.34127240e+00  -1.31297673e+00]
 [ -1.1

ValueError: Found input variables with inconsistent numbers of samples: [112, 37]